environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64


platform:
    - x64

install:
    - set

    - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - set PYTHONUNBUFFERED=1
    - set CPU_COUNT=2

    - conda config --set show_channel_urls true

    - conda install --quiet --yes conda-build

    - conda info
    - conda config --get


# Skip .NET project specific build phase.
build: off

test_script:
    - conda build %APPVEYOR_BUILD_FOLDER%\recipes\eman -c cryoem -c defaults -c conda-forge
