package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py

  commands:
    - e2version.py
    - e2speedtest.py
    - test -f ${PREFIX}/examples/mpi_test.py                        # [not win]
    - mpirun -n 4 $(which python) ${PREFIX}/examples/mpi_test.py    # [not win]
    - if not exist %LIBRARY_PREFIX%\\examples\\mpi_test.py  exit 1  # [win]
    - bash tests/run_prog_tests.sh                                  # [not win]
    - python tests/test_EMAN2DIR.py
