package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "boost 1.63.*",
            "msinttypes",       # [win]
            "python 3.5.*",     # [win]
            "fftw",             # [win]
            "numpy",            # [win]
            "ftgl",             # [win]
            "freetype",         # [win]
            "gsl",              # [win]
            "hdf5",             # [win]
            "jpeg",             # [win]
            "libtiff",          # [win]
            "libpng",           # [win]
            "zlib",             # [win]
            "matplotlib",       # [win]
            "ipython",          # [win]
            "pyqt 4.*",         # [win]
            "pyopengl 3.1.0",   # [win]
            "theano",           # [win]
            "scikit-learn",     # [win]
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_to_test.txt
    - tests/test_EMAN2DIR.py

  commands:
    - e2version.py
    - e2speedtest.py
    - test -f ${PREFIX}/examples/mpi_test.py                        # [not win]
    - mpirun -n 4 $(which python) ${PREFIX}/examples/mpi_test.py    # [not win]
    - if not exist %LIBRARY_PREFIX%\\examples\\mpi_test.py  exit 1  # [win]
    - bash tests/run_prog_tests.sh                                  # [not win]
    - python tests/test_EMAN2DIR.py
